added some use of the AdWhirl View, but then get missing obj during linking "Undefined symbols for architecture i386:   "_OBJC_CLASS_$_AdWhirlView", referenced from:       objc-class-ref in testerAppDelegate.o ld: symbol(s) not found for architecture i386"